--Procedimiento almacenado 1
CREATE OR REPLACE PROCEDURE AGREGAR_CLIENTE(
  P_NOMBRE IN VARCHAR2,
  P_TELEFONO IN VARCHAR2,
  P_CORREO IN VARCHAR2
) AS
BEGIN
  INSERT INTO CLIENTES (NOMBRE, TELEFONO, CORREO)
  VALUES (P_NOMBRE, P_TELEFONO, P_CORREO);
END;
/

--Procedimiento almacenado 2
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CLIENTE(
  P_CLIENTE_ID IN NUMBER,
  P_NOMBRE IN VARCHAR2,
  P_TELEFONO IN VARCHAR2,
  P_CORREO IN VARCHAR2
) AS
BEGIN
  UPDATE CLIENTES
  SET NOMBRE = P_NOMBRE,
      TELEFONO = P_TELEFONO,
      CORREO = P_CORREO
  WHERE CLIENTE_ID = P_CLIENTE_ID;
END;
/

--Procedimiento almacenado 3
CREATE OR REPLACE PROCEDURE ELIMINAR_CLIENTE(P_CLIENTE_ID IN NUMBER) AS
BEGIN
  DELETE FROM CLIENTES WHERE CLIENTE_ID = P_CLIENTE_ID;
END;
/

--Procedimiento almacenado 4
CREATE OR REPLACE PROCEDURE AGREGAR_EMPLEADO(
  P_NOMBRE IN VARCHAR2,
  P_ROL IN VARCHAR2,
  P_USUARIO IN VARCHAR2,
  P_CONTRASENA IN VARCHAR2
) AS
BEGIN
  INSERT INTO EMPLEADOS (NOMBRE, ROL, USUARIO, CONTRASENA)
  VALUES (P_NOMBRE, P_ROL, P_USUARIO, P_CONTRASENA);
END;
/

--Procedimiento almacenado 5
CREATE OR REPLACE PROCEDURE AGREGAR_PRODUCTO(
  P_NOMBRE IN VARCHAR2,
  P_TIPO IN VARCHAR2,
  P_PRECIO IN NUMBER,
  P_DESCRIPCION IN VARCHAR2,
  P_ACTIVO IN VARCHAR2
) AS
BEGIN
  INSERT INTO PRODUCTOS (NOMBRE, TIPO, PRECIO, DESCRIPCION, ACTIVO)
  VALUES (P_NOMBRE, P_TIPO, P_PRECIO, P_DESCRIPCION, P_ACTIVO);
END;
/

--Procedimiento almacenado 6
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRECIO_PRODUCTO(
  P_PRODUCTO_ID IN NUMBER,
  P_PRECIO IN NUMBER
) AS
BEGIN
  UPDATE PRODUCTOS SET PRECIO = P_PRECIO WHERE PRODUCTO_ID = P_PRODUCTO_ID;
END;
/

--Procedimiento almacenado 7
CREATE OR REPLACE PROCEDURE CAMBIAR_ESTADO_PRODUCTO(
  P_PRODUCTO_ID IN NUMBER,
  P_ACTIVO IN VARCHAR2
) AS
BEGIN
  UPDATE PRODUCTOS SET ACTIVO = P_ACTIVO WHERE PRODUCTO_ID = P_PRODUCTO_ID;
END;
/

--Procedimiento almacenado 8
CREATE OR REPLACE PROCEDURE AGREGAR_INVENTARIO(
  P_PRODUCTO_ID IN NUMBER,
  P_EXISTENCIAS IN NUMBER,
  P_STOCK_MINIMO IN NUMBER
) AS
BEGIN
  INSERT INTO INVENTARIO (PRODUCTO_ID, EXISTENCIAS, STOCK_MINIMO)
  VALUES (P_PRODUCTO_ID, P_EXISTENCIAS, P_STOCK_MINIMO);
END;
/

--Procedimiento almacenado 9
CREATE OR REPLACE PROCEDURE ACTUALIZAR_STOCK(
  P_PRODUCTO_ID IN NUMBER,
  P_CANTIDAD IN NUMBER
) AS
BEGIN
  UPDATE INVENTARIO
  SET EXISTENCIAS = EXISTENCIAS + P_CANTIDAD
  WHERE PRODUCTO_ID = P_PRODUCTO_ID;
END;
/

--Procedimiento almacenado 10
CREATE OR REPLACE PROCEDURE CREAR_PEDIDO(
  P_CLIENTE_ID IN NUMBER,
  P_EMPLEADO_ID IN NUMBER,
  P_TIPO_SERVICIO IN VARCHAR2,
  P_ESTADO IN VARCHAR2 DEFAULT 'PENDIENTE'
) AS
BEGIN
  INSERT INTO PEDIDOS (CLIENTE_ID, EMPLEADO_ID, FECHA, ESTADO, TIPO_SERVICIO)
  VALUES (P_CLIENTE_ID, P_EMPLEADO_ID, SYSDATE, P_ESTADO, P_TIPO_SERVICIO);
END;
/

--Procedimiento almacenado 11
CREATE OR REPLACE PROCEDURE AGREGAR_DETALLE_PEDIDO(
  P_PEDIDO_ID IN NUMBER,
  P_PRODUCTO_ID IN NUMBER,
  P_CANTIDAD IN NUMBER
) AS
  V_PRECIO NUMBER;
BEGIN
  SELECT PRECIO INTO V_PRECIO FROM PRODUCTOS WHERE PRODUCTO_ID = P_PRODUCTO_ID;

  INSERT INTO DETALLE_PEDIDO (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, SUBTOTAL)
  VALUES (P_PEDIDO_ID, P_PRODUCTO_ID, P_CANTIDAD, P_CANTIDAD * V_PRECIO);

  UPDATE INVENTARIO
  SET EXISTENCIAS = EXISTENCIAS - P_CANTIDAD
  WHERE PRODUCTO_ID = P_PRODUCTO_ID;
END;
/

--Procedimiento almacenado 12
CREATE OR REPLACE PROCEDURE CALCULAR_TOTAL_PEDIDO(
  P_PEDIDO_ID IN NUMBER,
  P_TOTAL OUT NUMBER
) AS
BEGIN
  SELECT SUM(SUBTOTAL)
  INTO P_TOTAL
  FROM DETALLE_PEDIDO
  WHERE PEDIDO_ID = P_PEDIDO_ID;
END;
/

--Procedimiento almacenado 13
CREATE OR REPLACE PROCEDURE GENERAR_FACTURA(
  P_PEDIDO_ID IN NUMBER,
  P_DESCUENTO IN NUMBER DEFAULT 0
) AS
  V_TOTAL NUMBER;
BEGIN
  CALCULAR_TOTAL_PEDIDO(P_PEDIDO_ID, V_TOTAL);
  V_TOTAL := V_TOTAL - (V_TOTAL * (P_DESCUENTO / 100));

  INSERT INTO FACTURAS (PEDIDO_ID, FECHA, TOTAL, DESCUENTO_APLICADO)
  VALUES (P_PEDIDO_ID, SYSDATE, V_TOTAL, P_DESCUENTO);
END;
/

--Procedimiento almacenado 14
CREATE OR REPLACE PROCEDURE ACTUALIZAR_ESTADO_PEDIDO(
  P_PEDIDO_ID IN NUMBER,
  P_ESTADO IN VARCHAR2
) AS
BEGIN
  UPDATE PEDIDOS SET ESTADO = P_ESTADO WHERE PEDIDO_ID = P_PEDIDO_ID;
END;
/
--Procedimiento almacenado 15
CREATE OR REPLACE PROCEDURE CANCELAR_PEDIDO(P_PEDIDO_ID IN NUMBER) AS
BEGIN
  UPDATE PEDIDOS SET ESTADO = 'CANCELADO' WHERE PEDIDO_ID = P_PEDIDO_ID;
END;
/

--Procedimiento almacenado 16
CREATE OR REPLACE PROCEDURE REPORTE_VENTAS_FECHA(
  P_FECHA_INICIO IN DATE,
  P_FECHA_FIN IN DATE,
  P_TOTAL OUT NUMBER
) AS
BEGIN
  SELECT SUM(TOTAL)
  INTO P_TOTAL
  FROM FACTURAS
  WHERE FECHA BETWEEN P_FECHA_INICIO AND P_FECHA_FIN;
END;
/

--Procedimiento almacenado 17 
CREATE OR REPLACE PROCEDURE PRODUCTOS_MAS_VENDIDOS(
  P_LIMITE IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_RESULTADO FOR
    SELECT P.PRODUCTO_ID,
           P.NOMBRE,
           SUM(D.CANTIDAD) AS TOTAL_VENDIDO
    FROM DETALLE_PEDIDO D
    JOIN PRODUCTOS P ON D.PRODUCTO_ID = P.PRODUCTO_ID
    GROUP BY P.PRODUCTO_ID, P.NOMBRE
    ORDER BY TOTAL_VENDIDO DESC
    FETCH FIRST P_LIMITE ROWS ONLY;
END;
/

VARIABLE rc REFCURSOR;
EXEC PRODUCTOS_MAS_VENDIDOS(5, :rc);
PRINT rc;

--Procedimiento almacenado 18 
CREATE OR REPLACE PROCEDURE PRODUCTOS_BAJO_STOCK(
  P_RESULTADO OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_RESULTADO FOR
    SELECT P.PRODUCTO_ID,
           P.NOMBRE,
           I.EXISTENCIAS,
           I.STOCK_MINIMO
    FROM INVENTARIO I
    JOIN PRODUCTOS P ON I.PRODUCTO_ID = P.PRODUCTO_ID
    WHERE I.EXISTENCIAS <= I.STOCK_MINIMO;
END;
/

VARIABLE rc REFCURSOR;
EXEC PRODUCTOS_BAJO_STOCK(:rc);
PRINT rc;

--Procedimiento almacenado 19
CREATE OR REPLACE PROCEDURE VENTAS_POR_EMPLEADO(
  P_EMPLEADO_ID IN NUMBER,
  P_TOTAL OUT NUMBER
) AS
BEGIN
  SELECT SUM(F.TOTAL)
  INTO P_TOTAL
  FROM FACTURAS F
  JOIN PEDIDOS P ON F.PEDIDO_ID = P.PEDIDO_ID
  WHERE P.EMPLEADO_ID = P_EMPLEADO_ID;
END;
/

--Procedimiento almacenado 20
CREATE OR REPLACE PROCEDURE REGISTRAR_REPORTE(
  P_FACTURA_ID IN NUMBER,
  P_PRODUCTO_ID IN NUMBER,
  P_PEDIDO_ID IN NUMBER,
  P_FECHA_INICIO IN DATE,
  P_FECHA_FIN IN DATE,
  P_VENTAS_TOTALES IN NUMBER,
  P_PRODUCTOS_MAS IN VARCHAR2,
  P_PRODUCTOS_MENOS IN VARCHAR2
) AS
BEGIN
  INSERT INTO REPORTES (
    FACTURA_ID, PRODUCTO_ID, PEDIDO_ID,
    FECHA_INICIO, FECHA_FIN, VENTAS_TOTALES,
    PRODUCTOS_MAS_VENDIDOS, PRODUCTOS_MENOS_VENDIDOS
  )
  VALUES (
    P_FACTURA_ID, P_PRODUCTO_ID, P_PEDIDO_ID,
    P_FECHA_INICIO, P_FECHA_FIN, P_VENTAS_TOTALES,
    P_PRODUCTOS_MAS, P_PRODUCTOS_MENOS
  );
END;
/

--Procedimiento almacenado 21
CREATE OR REPLACE PROCEDURE RESETEAR_CONTRASENA(
  P_EMPLEADO_ID IN NUMBER,
  P_NUEVA_CONTRASENA IN VARCHAR2
) AS
BEGIN
  UPDATE EMPLEADOS SET CONTRASENA = P_NUEVA_CONTRASENA WHERE EMPLEADO_ID = P_EMPLEADO_ID;
END;
/

--Procedimiento almacenado 22
CREATE OR REPLACE PROCEDURE CAMBIAR_ROL_EMPLEADO(
  P_EMPLEADO_ID IN NUMBER,
  P_NUEVO_ROL IN VARCHAR2
) AS
BEGIN
  UPDATE EMPLEADOS SET ROL = P_NUEVO_ROL WHERE EMPLEADO_ID = P_EMPLEADO_ID;
END;
/

--Procedimiento almacenado 23
CREATE OR REPLACE PROCEDURE VALIDAR_USUARIO(
  P_USUARIO IN VARCHAR2,
  P_CONTRASENA IN VARCHAR2,
  P_VALIDO OUT NUMBER
) AS
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
  FROM EMPLEADOS
  WHERE USUARIO = P_USUARIO AND CONTRASENA = P_CONTRASENA;

  P_VALIDO := CASE WHEN V_COUNT > 0 THEN 1 ELSE 0 END;
END;
/

--Procedimiento almacenado 24
CREATE OR REPLACE PROCEDURE REABASTECER_PRODUCTO(
  P_PRODUCTO_ID IN NUMBER,
  P_CANTIDAD IN NUMBER
) AS
BEGIN
  UPDATE INVENTARIO
  SET EXISTENCIAS = EXISTENCIAS + P_CANTIDAD
  WHERE PRODUCTO_ID = P_PRODUCTO_ID;
END;
/

--Procedimiento almacenado 25
CREATE OR REPLACE PROCEDURE ELIMINAR_FACTURA(P_FACTURA_ID IN NUMBER) AS
BEGIN
  DELETE FROM FACTURAS WHERE FACTURA_ID = P_FACTURA_ID;
END;
/
