--Procedimiento almacenado 1
CREATE OR REPLACE PROCEDURE AGREGAR_CLIENTE(
  P_NOMBRE IN VARCHAR2,
  P_TELEFONO IN VARCHAR2,
  P_CORREO IN VARCHAR2
) AS
BEGIN
  INSERT INTO CLIENTES (NOMBRE, TELEFONO, CORREO)
  VALUES (P_NOMBRE, P_TELEFONO, P_CORREO);

  DBMS_OUTPUT.PUT_LINE('CLIENTE REGISTRADO: ' || P_NOMBRE);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL AGREGAR CLIENTE: ' || SQLERRM);
END;
/

BEGIN
  AGREGAR_CLIENTE('Carlos López', '555-1234', 'carlos@test.com');
END;
/

--Procedimiento almacenado 2
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CLIENTE(
  P_CLIENTE_ID IN NUMBER,
  P_NOMBRE IN VARCHAR2,
  P_TELEFONO IN VARCHAR2,
  P_CORREO IN VARCHAR2
) AS
BEGIN
  UPDATE CLIENTES
  SET NOMBRE = P_NOMBRE,
      TELEFONO = P_TELEFONO,
      CORREO = P_CORREO
  WHERE CLIENTE_ID = P_CLIENTE_ID;

  DBMS_OUTPUT.PUT_LINE('CLIENTE ACTUALIZADO: ' || P_CLIENTE_ID);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR CLIENTE: ' || SQLERRM);
END;
/

BEGIN
  ACTUALIZAR_CLIENTE(1, 'Carlos Lopez', '555-8888', 'nuevo@test.com');
END;
/

--Procedimiento almacenado 3
CREATE OR REPLACE PROCEDURE ELIMINAR_CLIENTE(P_CLIENTE_ID IN NUMBER) AS
BEGIN
  DELETE FROM CLIENTES WHERE CLIENTE_ID = P_CLIENTE_ID;
  DBMS_OUTPUT.PUT_LINE('CLIENTE ELIMINADO: ' || P_CLIENTE_ID);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR CLIENTE: ' || SQLERRM);
END;
/

BEGIN
  ELIMINAR_CLIENTE(1);
END;
/

--Procedimiento almacenado 4
CREATE OR REPLACE PROCEDURE AGREGAR_EMPLEADO(
  P_NOMBRE IN VARCHAR2,
  P_ROL IN VARCHAR2,
  P_USUARIO IN VARCHAR2,
  P_CONTRASENA IN VARCHAR2
) AS
BEGIN
  INSERT INTO EMPLEADOS (NOMBRE, ROL, USUARIO, CONTRASENA)
  VALUES (P_NOMBRE, P_ROL, P_USUARIO, P_CONTRASENA);

  DBMS_OUTPUT.PUT_LINE('EMPLEADO AGREGADO: ' || P_NOMBRE);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL AGREGAR EMPLEADO: ' || SQLERRM);
END;
/

BEGIN
  AGREGAR_EMPLEADO('Ana Torres', 'VENTAS', 'atorres', '12345');
END;
/

--Procedimiento almacenado 5
CREATE OR REPLACE PROCEDURE AGREGAR_PRODUCTO(
  P_NOMBRE IN VARCHAR2,
  P_TIPO IN VARCHAR2,
  P_PRECIO IN NUMBER,
  P_DESCRIPCION IN VARCHAR2,
  P_ACTIVO IN VARCHAR2
) AS
BEGIN
  INSERT INTO PRODUCTOS (NOMBRE, TIPO, PRECIO, DESCRIPCION, ACTIVO)
  VALUES (P_NOMBRE, P_TIPO, P_PRECIO, P_DESCRIPCION, P_ACTIVO);

  DBMS_OUTPUT.PUT_LINE('PRODUCTO CREADO: ' || P_NOMBRE);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL AGREGAR PRODUCTO: ' || SQLERRM);
END;
/

BEGIN
  AGREGAR_PRODUCTO('Taco al Pastor', 'COMIDA', 18.50, 'Taco tradicional', 'SI');
END;
/

--Procedimiento almacenado 6
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRECIO_PRODUCTO(
  P_PRODUCTO_ID IN NUMBER,
  P_PRECIO IN NUMBER
) AS
BEGIN
  UPDATE PRODUCTOS SET PRECIO = P_PRECIO WHERE PRODUCTO_ID = P_PRODUCTO_ID;
  DBMS_OUTPUT.PUT_LINE('PRECIO ACTUALIZADO. PRODUCTO: ' || P_PRODUCTO_ID);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR PRECIO: ' || SQLERRM);
END;
/

BEGIN
  ACTUALIZAR_PRECIO_PRODUCTO(1, 20.00);
END;
/

--Procedimiento almacenado 7
CREATE OR REPLACE PROCEDURE CAMBIAR_ESTADO_PRODUCTO(
  P_PRODUCTO_ID IN NUMBER,
  P_ACTIVO IN VARCHAR2
) AS
BEGIN
  UPDATE PRODUCTOS SET ACTIVO = P_ACTIVO WHERE PRODUCTO_ID = P_PRODUCTO_ID;
  DBMS_OUTPUT.PUT_LINE('ESTADO CAMBIADO. PRODUCTO: ' || P_PRODUCTO_ID);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO: ' || SQLERRM);
END;
/

BEGIN
  CAMBIAR_ESTADO_PRODUCTO(1, 'NO');
END;
/

--Procedimiento almacenado 8
CREATE OR REPLACE PROCEDURE AGREGAR_INVENTARIO(
  P_PRODUCTO_ID IN NUMBER,
  P_EXISTENCIAS IN NUMBER,
  P_STOCK_MINIMO IN NUMBER
) AS
BEGIN
  INSERT INTO INVENTARIO (PRODUCTO_ID, EXISTENCIAS, STOCK_MINIMO)
  VALUES (P_PRODUCTO_ID, P_EXISTENCIAS, P_STOCK_MINIMO);

  DBMS_OUTPUT.PUT_LINE('INVENTARIO CREADO PARA PRODUCTO: ' || P_PRODUCTO_ID);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL AGREGAR INVENTARIO: ' || SQLERRM);
END;
/

BEGIN
  AGREGAR_INVENTARIO(1, 100, 20);
END;
/

--Procedimiento almacenado 9
CREATE OR REPLACE PROCEDURE ACTUALIZAR_STOCK(
  P_PRODUCTO_ID IN NUMBER,
  P_CANTIDAD IN NUMBER
) AS
BEGIN
  UPDATE INVENTARIO
  SET EXISTENCIAS = EXISTENCIAS + P_CANTIDAD
  WHERE PRODUCTO_ID = P_PRODUCTO_ID;

  DBMS_OUTPUT.PUT_LINE('STOCK ACTUALIZADO PARA PRODUCTO: ' || P_PRODUCTO_ID);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL ACTUALIZAR STOCK: ' || SQLERRM);
END;
/

BEGIN
  ACTUALIZAR_STOCK(1, 10);
END;
/

--Procedimiento almacenado 10
CREATE OR REPLACE PROCEDURE CREAR_PEDIDO(
  P_CLIENTE_ID IN NUMBER,
  P_EMPLEADO_ID IN NUMBER,
  P_TIPO_SERVICIO IN VARCHAR2,
  P_ESTADO IN VARCHAR2 DEFAULT 'PENDIENTE'
) AS
BEGIN
  INSERT INTO PEDIDOS (CLIENTE_ID, EMPLEADO_ID, FECHA, ESTADO, TIPO_SERVICIO)
  VALUES (P_CLIENTE_ID, P_EMPLEADO_ID, SYSDATE, P_ESTADO, P_TIPO_SERVICIO);

  DBMS_OUTPUT.PUT_LINE('PEDIDO CREADO PARA CLIENTE: ' || P_CLIENTE_ID);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL CREAR PEDIDO: ' || SQLERRM);
END;
/

BEGIN
  CREAR_PEDIDO(1, 1, 'PARA LLEVAR', 'PENDIENTE');
END;
/

--Procedimiento almacenado 11
CREATE OR REPLACE PROCEDURE AGREGAR_DETALLE_PEDIDO( 
  P_PEDIDO_ID IN NUMBER,
  P_PRODUCTO_ID IN NUMBER,
  P_CANTIDAD IN NUMBER
) AS
  V_PRECIO NUMBER;
BEGIN
  -- Obtener precio del producto
  SELECT PRECIO INTO V_PRECIO 
  FROM PRODUCTOS 
  WHERE PRODUCTO_ID = P_PRODUCTO_ID;

  -- Insertar detalle
  INSERT INTO DETALLE_PEDIDO (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, SUBTOTAL)
  VALUES (P_PEDIDO_ID, P_PRODUCTO_ID, P_CANTIDAD, P_CANTIDAD * V_PRECIO);

  -- Actualizar inventario
  UPDATE INVENTARIO
  SET EXISTENCIAS = EXISTENCIAS - P_CANTIDAD
  WHERE PRODUCTO_ID = P_PRODUCTO_ID;

  DBMS_OUTPUT.PUT_LINE('DETALLE AGREGADO:');
  DBMS_OUTPUT.PUT_LINE('- PEDIDO: ' || P_PEDIDO_ID);
  DBMS_OUTPUT.PUT_LINE('- PRODUCTO: ' || P_PRODUCTO_ID);
  DBMS_OUTPUT.PUT_LINE('- CANTIDAD: ' || P_CANTIDAD);
  DBMS_OUTPUT.PUT_LINE('- SUBTOTAL: $' || (P_CANTIDAD * V_PRECIO));

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: PRODUCTO NO EXISTE (' || P_PRODUCTO_ID || ')');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DETALLE: ' || SQLERRM);
END;
/

BEGIN
  AGREGAR_DETALLE_PEDIDO(1, 1, 3);
END;
/

--Procedimiento almacenado 12
CREATE OR REPLACE PROCEDURE CALCULAR_TOTAL_PEDIDO(
  P_PEDIDO_ID IN NUMBER,
  P_TOTAL OUT NUMBER
) AS
BEGIN
  SELECT SUM(SUBTOTAL)
  INTO P_TOTAL
  FROM DETALLE_PEDIDO
  WHERE PEDIDO_ID = P_PEDIDO_ID;

  DBMS_OUTPUT.PUT_LINE('TOTAL CALCULADO: ' || P_TOTAL);
END;
/

DECLARE
  V_TOTAL NUMBER;
BEGIN
  CALCULAR_TOTAL_PEDIDO(1, V_TOTAL);
  DBMS_OUTPUT.PUT_LINE('TOTAL CALCULADO: ' || V_TOTAL);
END;
/

--Procedimiento almacenado 13
CREATE OR REPLACE PROCEDURE GENERAR_FACTURA( 
  P_PEDIDO_ID IN NUMBER,
  P_DESCUENTO IN NUMBER DEFAULT 0
) AS
  V_TOTAL NUMBER;
  V_TOTAL_DESCONTADO NUMBER;
BEGIN
  -- Obtener total del pedido
  CALCULAR_TOTAL_PEDIDO(P_PEDIDO_ID, V_TOTAL);

  -- Aplicar descuento
  V_TOTAL_DESCONTADO := V_TOTAL - (V_TOTAL * (P_DESCUENTO / 100));

  -- Insertar factura
  INSERT INTO FACTURAS (PEDIDO_ID, FECHA, TOTAL, DESCUENTO_APLICADO)
  VALUES (P_PEDIDO_ID, SYSDATE, V_TOTAL_DESCONTADO, P_DESCUENTO);

  -- SALIDA
  DBMS_OUTPUT.PUT_LINE('FACTURA GENERADA:');
  DBMS_OUTPUT.PUT_LINE('- PEDIDO: ' || P_PEDIDO_ID);
  DBMS_OUTPUT.PUT_LINE('- SUBTOTAL: $' || V_TOTAL);
  DBMS_OUTPUT.PUT_LINE('- DESCUENTO: ' || P_DESCUENTO || '%');
  DBMS_OUTPUT.PUT_LINE('- TOTAL FACTURADO: $' || V_TOTAL_DESCONTADO);
  DBMS_OUTPUT.PUT_LINE('- FECHA: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI'));

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: EL PEDIDO NO EXISTE (' || P_PEDIDO_ID || ')');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL GENERAR FACTURA: ' || SQLERRM);
END;
/

BEGIN
  GENERAR_FACTURA(1, 10);
END;
/

--Procedimiento almacenado 14
CREATE OR REPLACE PROCEDURE ACTUALIZAR_ESTADO_PEDIDO(
  P_PEDIDO_ID IN NUMBER,
  P_ESTADO IN VARCHAR2
) AS
BEGIN
  UPDATE PEDIDOS SET ESTADO = P_ESTADO WHERE PEDIDO_ID = P_PEDIDO_ID;

  DBMS_OUTPUT.PUT_LINE('ESTADO PEDIDO ACTUALIZADO A: ' || P_ESTADO);
END;
/

BEGIN
  ACTUALIZAR_ESTADO_PEDIDO(1, 'ENTREGADO');
END;
/

--Procedimiento almacenado 15
CREATE OR REPLACE PROCEDURE CANCELAR_PEDIDO(P_PEDIDO_ID IN NUMBER) AS
BEGIN
  UPDATE PEDIDOS SET ESTADO = 'CANCELADO' WHERE PEDIDO_ID = P_PEDIDO_ID;
  DBMS_OUTPUT.PUT_LINE('PEDIDO CANCELADO: ' || P_PEDIDO_ID);
END;
/

BEGIN
  CANCELAR_PEDIDO(1);
END;
/

--Procedimiento almacenado 16
CREATE OR REPLACE PROCEDURE REPORTE_VENTAS_FECHA( 
  P_FECHA_INICIO IN DATE,
  P_FECHA_FIN IN DATE,
  P_TOTAL OUT NUMBER
) AS
BEGIN
  SELECT NVL(SUM(TOTAL), 0)
  INTO P_TOTAL
  FROM FACTURAS
  WHERE FECHA BETWEEN P_FECHA_INICIO AND P_FECHA_FIN;

  DBMS_OUTPUT.PUT_LINE('REPORTE DE VENTAS');
  DBMS_OUTPUT.PUT_LINE('- DESDE: ' || TO_CHAR(P_FECHA_INICIO, 'DD/MM/YYYY'));
  DBMS_OUTPUT.PUT_LINE('- HASTA: ' || TO_CHAR(P_FECHA_FIN, 'DD/MM/YYYY'));
  DBMS_OUTPUT.PUT_LINE('- TOTAL VENTAS: $' || P_TOTAL);

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL GENERAR REPORTE: ' || SQLERRM);
END;
/

DECLARE
  V_TOTAL NUMBER;
BEGIN
  REPORTE_VENTAS_FECHA(SYSDATE - 30, SYSDATE, V_TOTAL);
  DBMS_OUTPUT.PUT_LINE('VENTAS TOTALES: ' || V_TOTAL);
END;
/

--Procedimiento almacenado 17 
CREATE OR REPLACE PROCEDURE PRODUCTOS_MAS_VENDIDOS( 
  P_LIMITE IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_RESULTADO FOR
    SELECT P.PRODUCTO_ID,
           P.NOMBRE,
           SUM(D.CANTIDAD) AS TOTAL_VENDIDO
    FROM DETALLE_PEDIDO D
    JOIN PRODUCTOS P ON D.PRODUCTO_ID = P.PRODUCTO_ID
    GROUP BY P.PRODUCTO_ID, P.NOMBRE
    ORDER BY TOTAL_VENDIDO DESC
    FETCH FIRST P_LIMITE ROWS ONLY;

  DBMS_OUTPUT.PUT_LINE('CONSULTA GENERADA: PRODUCTOS MÁS VENDIDOS (TOP ' || P_LIMITE || ')');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL CONSULTAR PRODUCTOS MAS VENDIDOS: ' || SQLERRM);
END;
/

DECLARE
  V_CURSOR SYS_REFCURSOR;
  V_ID NUMBER;
  V_NOMBRE VARCHAR2(100);
  V_TOTAL NUMBER;
BEGIN
  PRODUCTOS_MAS_VENDIDOS(5, V_CURSOR);

  LOOP
    FETCH V_CURSOR INTO V_ID, V_NOMBRE, V_TOTAL;
    EXIT WHEN V_CURSOR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('PRODUCTO: ' || V_NOMBRE || ' - VENDIDOS: ' || V_TOTAL);
  END LOOP;
END;
/

--Procedimiento almacenado 18 
CREATE OR REPLACE PROCEDURE PRODUCTOS_BAJO_STOCK(
  P_RESULTADO OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_RESULTADO FOR
    SELECT P.PRODUCTO_ID,
           P.NOMBRE,
           I.EXISTENCIAS,
           I.STOCK_MINIMO
    FROM INVENTARIO I
    JOIN PRODUCTOS P ON I.PRODUCTO_ID = P.PRODUCTO_ID
    WHERE I.EXISTENCIAS <= I.STOCK_MINIMO;

  DBMS_OUTPUT.PUT_LINE('CONSULTA GENERADA: PRODUCTOS BAJO STOCK');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL CONSULTAR BAJO STOCK: ' || SQLERRM);
END;
/

DECLARE
  V_CURSOR SYS_REFCURSOR;
  V_ID NUMBER;
  V_NOMBRE VARCHAR2(100);
  V_EX NUMBER;
  V_MIN NUMBER;
BEGIN
  PRODUCTOS_BAJO_STOCK(V_CURSOR);

  LOOP
    FETCH V_CURSOR INTO V_ID, V_NOMBRE, V_EX, V_MIN;
    EXIT WHEN V_CURSOR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('PRODUCTO: ' || V_NOMBRE || ' EXISTENCIAS: ' || V_EX);
  END LOOP;
END;
/

--Procedimiento almacenado 19
CREATE OR REPLACE PROCEDURE VENTAS_POR_EMPLEADO(
  P_EMPLEADO_ID IN NUMBER,
  P_TOTAL OUT NUMBER
) AS
BEGIN
  SELECT NVL(SUM(F.TOTAL), 0)
  INTO P_TOTAL
  FROM FACTURAS F
  JOIN PEDIDOS P ON F.PEDIDO_ID = P.PEDIDO_ID
  WHERE P.EMPLEADO_ID = P_EMPLEADO_ID;

  DBMS_OUTPUT.PUT_LINE('VENTAS POR EMPLEADO');
  DBMS_OUTPUT.PUT_LINE('- EMPLEADO ID: ' || P_EMPLEADO_ID);
  DBMS_OUTPUT.PUT_LINE('- TOTAL VENTAS: $' || P_TOTAL);

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL CONSULTAR VENTAS DE EMPLEADO: ' || SQLERRM);
END;
/

DECLARE
  V_TOTAL NUMBER;
BEGIN
  VENTAS_POR_EMPLEADO(1, V_TOTAL);
  DBMS_OUTPUT.PUT_LINE('VENTAS DE EMPLEADO: ' || V_TOTAL);
END;
/

--Procedimiento almacenado 20
CREATE OR REPLACE PROCEDURE REGISTRAR_REPORTE(
  P_FACTURA_ID IN NUMBER,
  P_PRODUCTO_ID IN NUMBER,
  P_PEDIDO_ID IN NUMBER,
  P_FECHA_INICIO IN DATE,
  P_FECHA_FIN IN DATE,
  P_VENTAS_TOTALES IN NUMBER,
  P_PRODUCTOS_MAS IN VARCHAR2,
  P_PRODUCTOS_MENOS IN VARCHAR2
) AS
BEGIN
  INSERT INTO REPORTES (
    FACTURA_ID, PRODUCTO_ID, PEDIDO_ID,
    FECHA_INICIO, FECHA_FIN, VENTAS_TOTALES,
    PRODUCTOS_MAS_VENDIDOS, PRODUCTOS_MENOS_VENDIDOS
  )
  VALUES (
    P_FACTURA_ID, P_PRODUCTO_ID, P_PEDIDO_ID,
    P_FECHA_INICIO, P_FECHA_FIN, P_VENTAS_TOTALES,
    P_PRODUCTOS_MAS, P_PRODUCTOS_MENOS
  );

  DBMS_OUTPUT.PUT_LINE('REPORTE REGISTRADO:');
  DBMS_OUTPUT.PUT_LINE('- FACTURA: ' || P_FACTURA_ID);
  DBMS_OUTPUT.PUT_LINE('- PEDIDO: ' || P_PEDIDO_ID);
  DBMS_OUTPUT.PUT_LINE('- PRODUCTO: ' || P_PRODUCTO_ID);
  DBMS_OUTPUT.PUT_LINE('- VENTAS TOTALES: $' || P_VENTAS_TOTALES);
  DBMS_OUTPUT.PUT_LINE('- PRODUCTOS MÁS VENDIDOS: ' || P_PRODUCTOS_MAS);
  DBMS_OUTPUT.PUT_LINE('- PRODUCTOS MENOS VENDIDOS: ' || P_PRODUCTOS_MENOS);

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL REGISTRAR REPORTE: ' || SQLERRM);
END;
/

BEGIN
  REGISTRAR_REPORTE(1, 1, 1, SYSDATE - 10, SYSDATE, 500, 'Tacos', 'Refrescos');
END;
/

--Procedimiento almacenado 21
CREATE OR REPLACE PROCEDURE RESETEAR_CONTRASENA(
  P_EMPLEADO_ID IN NUMBER,
  P_NUEVA_CONTRASENA IN VARCHAR2
) AS
BEGIN
  UPDATE EMPLEADOS SET CONTRASENA = P_NUEVA_CONTRASENA WHERE EMPLEADO_ID = P_EMPLEADO_ID;
  DBMS_OUTPUT.PUT_LINE('CONTRASEÑA RESETEADA PARA EMPLEADO: ' || P_EMPLEADO_ID);
END;
/

BEGIN
  RESETEAR_CONTRASENA(1, 'NUEVA_1234');
END;
/

--Procedimiento almacenado 22
CREATE OR REPLACE PROCEDURE CAMBIAR_ROL_EMPLEADO(
  P_EMPLEADO_ID IN NUMBER,
  P_NUEVO_ROL IN VARCHAR2
) AS
BEGIN
  UPDATE EMPLEADOS
  SET ROL = P_NUEVO_ROL
  WHERE EMPLEADO_ID = P_EMPLEADO_ID;

  IF SQL%ROWCOUNT = 0 THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRÓ EL EMPLEADO ID: ' || P_EMPLEADO_ID);
  ELSE
    DBMS_OUTPUT.PUT_LINE('ROL ACTUALIZADO:');
    DBMS_OUTPUT.PUT_LINE('- EMPLEADO: ' || P_EMPLEADO_ID);
    DBMS_OUTPUT.PUT_LINE('- NUEVO ROL: ' || P_NUEVO_ROL);
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ROL: ' || SQLERRM);
END;
/

BEGIN
  CAMBIAR_ROL_EMPLEADO(1, 'ADMIN');
END;
/

--Procedimiento almacenado 23
CREATE OR REPLACE PROCEDURE VALIDAR_USUARIO(
  P_USUARIO IN VARCHAR2,
  P_CONTRASENA IN VARCHAR2,
  P_VALIDO OUT NUMBER
) AS
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT
  FROM EMPLEADOS
  WHERE USUARIO = P_USUARIO AND CONTRASENA = P_CONTRASENA;

  P_VALIDO := CASE WHEN V_COUNT > 0 THEN 1 ELSE 0 END;

  IF P_VALIDO = 1 THEN
    DBMS_OUTPUT.PUT_LINE('USUARIO VALIDADO: ' || P_USUARIO);
  ELSE
    DBMS_OUTPUT.PUT_LINE('CREDENCIALES INVALIDAS PARA USUARIO: ' || P_USUARIO);
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR VALIDANDO USUARIO: ' || SQLERRM);
END;
/

DECLARE
  V_VALIDO NUMBER;
BEGIN
  VALIDAR_USUARIO('atorres','12345', V_VALIDO);
  DBMS_OUTPUT.PUT_LINE('¿USUARIO VALIDO? ' || V_VALIDO);
END;
/

--Procedimiento almacenado 24
CREATE OR REPLACE PROCEDURE REABASTECER_PRODUCTO(
  P_PRODUCTO_ID IN NUMBER,
  P_CANTIDAD IN NUMBER
) AS
BEGIN
  UPDATE INVENTARIO
  SET EXISTENCIAS = EXISTENCIAS + P_CANTIDAD
  WHERE PRODUCTO_ID = P_PRODUCTO_ID;

  IF SQL%ROWCOUNT = 0 THEN
    DBMS_OUTPUT.PUT_LINE('NO EXISTE PRODUCTO EN INVENTARIO: ' || P_PRODUCTO_ID);
  ELSE
    DBMS_OUTPUT.PUT_LINE('PRODUCTO REABASTECIDO:');
    DBMS_OUTPUT.PUT_LINE('- PRODUCTO: ' || P_PRODUCTO_ID);
    DBMS_OUTPUT.PUT_LINE('- CANTIDAD AGREGADA: ' || P_CANTIDAD);
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR AL REABASTECER: ' || SQLERRM);
END;
/

BEGIN
  REABASTECER_PRODUCTO(1, 50);
END;
/

--Procedimiento almacenado 25
CREATE OR REPLACE PROCEDURE ELIMINAR_FACTURA(P_FACTURA_ID IN NUMBER) AS
BEGIN
  DELETE FROM FACTURAS WHERE FACTURA_ID = P_FACTURA_ID;
  DBMS_OUTPUT.PUT_LINE('FACTURA ELIMINADA: ' || P_FACTURA_ID);
END;
/

BEGIN
  ELIMINAR_FACTURA(1);
END;
/


