--Trigger 1
CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_INVENTARIO_VENTA
AFTER INSERT ON DETALLE_PEDIDO
FOR EACH ROW
BEGIN
  UPDATE INVENTARIO
  SET EXISTENCIAS = EXISTENCIAS - :NEW.CANTIDAD
  WHERE PRODUCTO_ID = :NEW.PRODUCTO_ID;
END;
/

--Trigger 2
CREATE OR REPLACE TRIGGER TRG_VALIDAR_STOCK
BEFORE INSERT ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
  V_EXISTENCIAS NUMBER;
BEGIN
  SELECT EXISTENCIAS
  INTO V_EXISTENCIAS
  FROM INVENTARIO
  WHERE PRODUCTO_ID = :NEW.PRODUCTO_ID;

  IF :NEW.CANTIDAD > V_EXISTENCIAS THEN
    RAISE_APPLICATION_ERROR(-20001, 'No hay existencias suficientes en inventario.');
  END IF;
END;
/
--Trigger 3
CREATE OR REPLACE TRIGGER TRG_FECHA_PEDIDO
BEFORE INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
  IF :NEW.FECHA IS NULL THEN
    :NEW.FECHA := SYSDATE;
  END IF;
END;
/

--Trigger 4
CREATE OR REPLACE TRIGGER TRG_CALCULAR_SUBTOTAL
BEFORE INSERT ON DETALLE_PEDIDO
FOR EACH ROW
DECLARE
  V_PRECIO NUMBER;
BEGIN
  SELECT PRECIO INTO V_PRECIO
  FROM PRODUCTOS
  WHERE PRODUCTO_ID = :NEW.PRODUCTO_ID;

  :NEW.SUBTOTAL := :NEW.CANTIDAD * V_PRECIO;
END;
/

--Trigger 5
CREATE OR REPLACE TRIGGER TRG_GENERAR_REPORTE_AUTOMATICO
AFTER INSERT ON FACTURAS
FOR EACH ROW
DECLARE
  V_TOTAL_VENTAS NUMBER;
BEGIN
  SELECT SUM(SUBTOTAL)
  INTO V_TOTAL_VENTAS
  FROM DETALLE_PEDIDO
  WHERE PEDIDO_ID = :NEW.PEDIDO_ID;

  INSERT INTO REPORTES (
    FACTURA_ID,
    PEDIDO_ID,
    FECHA_INICIO,
    FECHA_FIN,
    VENTAS_TOTALES
  ) VALUES (
    :NEW.FACTURA_ID,
    :NEW.PEDIDO_ID,
    :NEW.FECHA,
    :NEW.FECHA,
    V_TOTAL_VENTAS
  );
END;
/

